### ISSUE TITLE
Any pointers on how to get past this? This is following the instructions in the readme 

### ISSUE THREAD

**Issue by mdcfrancis** [Keno/Cxx.jl#180] opened 2015-10-16 19:30 UTC
/home/michael/src/cxx/src/codegen.cpp: In function ‘llvm::Function* emit_function(jl_lambda_info_t*)’:
/home/michael/src/cxx/src/codegen.cpp:4480:108: error: no matching function for call to ‘llvm::DIBuilder::createSubroutineType(llvm::DIFi
             subrty = ctx.dbuilder->createSubroutineType(topfile,ctx.dbuilder->getOrCreateTypeArray(ditypes));
                                                                                                            ^
/home/michael/src/cxx/src/codegen.cpp:4480:108: note: candidate is:
In file included from /home/michael/src/cxx/src/codegen.cpp:46:0:
/home/michael/src/cxx/usr/include/llvm/IR/DIBuilder.h:382:23: note: llvm::DISubroutineType* llvm::DIBuilder::createSubroutineType(llvm::D
     DISubroutineType *createSubroutineType(DITypeRefArray ParameterTypes,
                       ^
/home/michael/src/cxx/usr/include/llvm/IR/DIBuilder.h:382:23: note:   no known conversion for argument 1 from ‘llvm::DIFile*’ to ‘llvm::D
/home/michael/src/cxx/src/codegen.cpp: In function ‘void init_julia_llvm_env(llvm::Module*)’:
/home/michael/src/cxx/src/codegen.cpp:5317:46: error: no matching function for call to ‘llvm::DIBuilder::createSubroutineType(llvm::DIFil
         dbuilder.getOrCreateTypeArray(diargs));
                                              ^
/home/michael/src/cxx/src/codegen.cpp:5317:46: note: candidate is:
In file included from /home/michael/src/cxx/src/codegen.cpp:46:0:
/home/michael/src/cxx/usr/include/llvm/IR/DIBuilder.h:382:23: note: llvm::DISubroutineType* llvm::DIBuilder::createSubroutineType(llvm::D
     DISubroutineType *createSubroutineType(DITypeRefArray ParameterTypes,
                       ^
/home/michael/src/cxx/usr/include/llvm/IR/DIBuilder.h:382:23: note:   no known conversion for argument 1 from ‘llvm::DIFile*’ to ‘llvm::D
make[1]: *** [codegen.o] Error 1
make: *** [julia-src-release] Error 2

**Comment by malmaud** [comment] 2015-10-17 13:37
Same; this is probably caused by a new breaking change on llvm trunk.

**Comment by mturok** [comment] 2015-10-19 12:24
Keno - how hard would it be to use a specific branch or tag from llvm when building here?

**Comment by Keno** [comment] 2015-10-19 21:34
Fixed in https://github.com/JuliaLang/julia/commit/7d2f7b50b35838cb06e31ccd9c369d15ecf00efb.

**Closed by Keno** 2015-10-19 21:34 UTC
