### ISSUE TITLE
Pkg.build error in OSX 10.10.4

### ISSUE THREAD

**Issue by ranjanan** [Keno/Cxx.jl#151] opened 2015-09-03 17:29 UTC
On the current master, I get the following build error:

```
julia> Pkg.build("Cxx")
INFO: Building Cxx
Tuning for julia installation at: /Users/ranjan/julia-4/usr/bin
    CC /Users/ranjan/.julia/v0.4/Cxx/deps/build/bootstrap.o
    LINK /Users/ranjan/.julia/v0.4/Cxx/deps/usr/lib/libcxxffi.dylib
Undefined symbols for architecture x86_64:
  "lldb_private::ObjCLanguage::Initialize()", referenced from:
      lldb_private::SystemInitializerFull::Initialize() in liblldbAPI.a(SystemInitializerFull.o)
  "lldb_private::ObjCLanguage::MethodName::GetSelector()", referenced from:
      DWARFASTParserClang::ParseChildMembers(lldb_private::SymbolContext const&, DWARFDIE const&, lldb_private::CompilerType&, lldb::LanguageType, std::__1::vector<clang::CXXBaseSpecifier*, std::__1::allocator<clang::CXXBaseSpecifier*> >&, std::__1::vector<int, std::__1::allocator<int> >&, DWARFDIECollection&, std::__1::vector<DWARFASTParserClang::DelayedAddObjCClassProperty, std::__1::allocator<DWARFASTParserClang::DelayedAddObjCClassProperty> >&, lldb::AccessType&, bool&, DWARFASTParserClang::LayoutInfo&) in liblldbPluginSymbolFileDWARF.a(DWARFASTParserClang.o)
      DWARFCompileUnit::Index(unsigned int, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&) in liblldbPluginSymbolFileDWARF.a(DWARFCompileUnit.o)
      lldb_private::Symtab::InitNameIndexes() in liblldbSymbol.a(Symtab.o)
  "lldb_private::ObjCLanguage::MethodName::GetClassName()", referenced from:
      DWARFASTParserClang::ParseTypeFromDWARF(lldb_private::SymbolContext const&, DWARFDIE const&, lldb_private::Log*, bool*) in liblldbPluginSymbolFileDWARF.a(DWARFASTParserClang.o)
      DWARFCompileUnit::Index(unsigned int, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&) in liblldbPluginSymbolFileDWARF.a(DWARFCompileUnit.o)
  "lldb_private::ObjCLanguage::MethodName::GetFullNames(std::__1::vector<lldb_private::ConstString, std::__1::allocator<lldb_private::ConstString> >&, bool)", referenced from:
lldb_private::BreakpointResolverName::AddNameLookup(lldb_private::ConstString const&, unsigned int) in liblldbBreakpoint.a(BreakpointResolverName.o)
  "lldb_private::ObjCLanguage::MethodName::GetClassNameWithCategory()", referenced from:
      DWARFCompileUnit::Index(unsigned int, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&) in liblldbPluginSymbolFileDWARF.a(DWARFCompileUnit.o)
  "lldb_private::ObjCLanguage::MethodName::GetFullNameWithoutCategory(bool)", referenced from:
      DWARFCompileUnit::Index(unsigned int, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&) in liblldbPluginSymbolFileDWARF.a(DWARFCompileUnit.o)
      lldb_private::Symtab::InitNameIndexes() in liblldbSymbol.a(Symtab.o)
  "lldb_private::ObjCLanguage::MethodName::SetName(char const*, bool)", referenced from:
      lldb_private::BreakpointResolverName::AddNameLookup(lldb_private::ConstString const&, unsigned int) in liblldbBreakpoint.a(BreakpointResolverName.o)
      DWARFASTParserClang::ParseTypeFromDWARF(lldb_private::SymbolContext const&, DWARFDIE const&, lldb_private::Log*, bool*) in liblldbPluginSymbolFileDWARF.a(DWARFASTParserClang.o)
      DWARFASTParserClang::ParseChildMembers(lldb_private::SymbolContext const&, DWARFDIE const&, lldb_private::CompilerType&, lldb::LanguageType, std::__1::vector<clang::CXXBaseSpecifier*, std::__1::allocator<clang::CXXBaseSpecifier*> >&, std::__1::vector<int, std::__1::allocator<int> >&, DWARFDIECollection&, std::__1::vector<DWARFASTParserClang::DelayedAddObjCClassProperty, std::__1::allocator<DWARFASTParserClang::DelayedAddObjCClassProperty> >&, lldb::AccessType&, bool&, DWARFASTParserClang::LayoutInfo&) in liblldbPluginSymbolFileDWARF.a(DWARFASTParserClang.o)
      DWARFCompileUnit::Index(unsigned int, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&, NameToDIE&) in liblldbPluginSymbolFileDWARF.a(DWARFCompileUnit.o)
      lldb_private::Symtab::InitNameIndexes() in liblldbSymbol.a(Symtab.o)
  "lldb_private::ObjCLanguage::Terminate()", referenced from:
      lldb_private::SystemInitializerFull::Terminate() in liblldbAPI.a(SystemInitializerFull.o)
  "lldb_private::CPlusPlusLanguage::Initialize()", referenced from:
      lldb_private::SystemInitializerFull::Initialize() in liblldbAPI.a(SystemInitializerFull.o)
  "lldb_private::CPlusPlusLanguage::MethodName::GetContext()", referenced from:
      lldb_private::Mangled::GetName(lldb::LanguageType, lldb_private::Mangled::NamePreference) const in liblldbCore.a(Mangled.o)
      lldb_private::Symtab::InitNameIndexes() in liblldbSymbol.a(Symtab.o)
  "lldb_private::CPlusPlusLanguage::MethodName::GetBasename()", referenced from:
      lldb_private::Mangled::GetName(lldb::LanguageType, lldb_private::Mangled::NamePreference) const in liblldbCore.a(Mangled.o)
      lldb_private::Module::PrepareForFunctionNameLookup(lldb_private::ConstString const&, unsigned int, lldb::LanguageType, lldb_private::ConstString&, unsigned int&, bool&) in liblldbCore.a(Module.o)
      lldb_private::Symtab::InitNameIndexes() in liblldbSymbol.a(Symtab.o)
  "lldb_private::CPlusPlusLanguage::MethodName::GetQualifiers()", referenced from:
      lldb_private::Module::PrepareForFunctionNameLookup(lldb_private::ConstString const&, unsigned int, lldb::LanguageType, lldb_private::ConstString&, unsigned int&, bool&) in liblldbCore.a(Module.o)
      lldb_private::Symtab::InitNameIndexes() in liblldbSymbol.a(Symtab.o)
  "lldb_private::CPlusPlusLanguage::MethodName::Parse()", referenced from:
      lldb_private::Module::PrepareForFunctionNameLookup(lldb_private::ConstString const&, unsigned int, lldb::LanguageType, lldb_private::ConstString&, unsigned int&, bool&) in liblldbCore.a(Module.o)
  "lldb_private::CPlusPlusLanguage::IsCPPMangledName(char const*)", referenced from:
      lldb_private::Module::PrepareForFunctionNameLookup(lldb_private::ConstString const&, unsigned int, lldb::LanguageType, lldb_private::ConstString&, unsigned int&, bool&) in liblldbCore.a(Module.o)
  "lldb_private::CPlusPlusLanguage::ExtractContextAndIdentifier(char const*, llvm::StringRef&, llvm::StringRef&)", referenced from:
      lldb_private::Module::PrepareForFunctionNameLookup(lldb_private::ConstString const&, unsigned int, lldb::LanguageType, lldb_private::ConstString&, unsigned int&, bool&) in liblldbCore.a(Module.o)
      SymbolFileDWARF::FindGlobalVariables(lldb_private::ConstString const&, lldb_private::CompilerDeclContext const*, bool, unsigned int, lldb_private::VariableList&) in liblldbPluginSymbolFileDWARF.a(SymbolFileDWARF.o)
  "lldb_private::CPlusPlusLanguage::Terminate()", referenced from:
      lldb_private::SystemInitializerFull::Terminate() in liblldbAPI.a(SystemInitializerFull.o)
  "lldb_private::ObjCPlusPlusLanguage::Initialize()", referenced from:
      lldb_private::SystemInitializerFull::Initialize() in liblldbAPI.a(SystemInitializerFull.o)
  "lldb_private::ObjCPlusPlusLanguage::Terminate()", referenced from:
      lldb_private::SystemInitializerFull::Terminate() in liblldbAPI.a(SystemInitializerFull.o)
  "lldb_private::ClangExpressionVariable::GetByteSize()", referenced from:
      EntityResultVariable::Dematerialize(std::__1::shared_ptr<lldb_private::ClangExpressionVariable>&, std::__1::shared_ptr<lldb_private::StackFrame>&, lldb_private::IRMemoryMap&, unsigned long long, unsigned long long, unsigned long long, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
      EntityPersistentVariable::Dematerialize(std::__1::shared_ptr<lldb_private::StackFrame>&, lldb_private::IRMemoryMap&, unsigned long long, unsigned long long, unsigned long long, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
      EntityPersistentVariable::DumpToLog(lldb_private::IRMemoryMap&, unsigned long long, lldb_private::Log*) in liblldbExpression.a(Materializer.o)
      EntityPersistentVariable::MakeAllocation(lldb_private::IRMemoryMap&, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
  "lldb_private::ClangExpressionVariable::ValueUpdated()", referenced from:
      EntityResultVariable::Dematerialize(std::__1::shared_ptr<lldb_private::ClangExpressionVariable>&, std::__1::shared_ptr<lldb_private::StackFrame>&, lldb_private::IRMemoryMap&, unsigned long long, unsigned long long, unsigned long long, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
      EntityPersistentVariable::Dematerialize(std::__1::shared_ptr<lldb_private::StackFrame>&, lldb_private::IRMemoryMap&, unsigned long long, unsigned long long, unsigned long long, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
  "lldb_private::ClangExpressionVariable::GetValueBytes()", referenced from:
      EntityResultVariable::Dematerialize(std::__1::shared_ptr<lldb_private::ClangExpressionVariable>&, std::__1::shared_ptr<lldb_private::StackFrame>&, lldb_private::IRMemoryMap&, unsigned long long, unsigned long long, unsigned long long, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
      EntityPersistentVariable::Dematerialize(std::__1::shared_ptr<lldb_private::StackFrame>&, lldb_private::IRMemoryMap&, unsigned long long, unsigned long long, unsigned long long, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
      EntityPersistentVariable::MakeAllocation(lldb_private::IRMemoryMap&, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
  "lldb_private::ClangExpressionVariable::GetValueObject()", referenced from:
      lldb_private::BreakpointLocation::ConditionSaysStop(lldb_private::ExecutionContext&, lldb_private::Error&) in liblldbBreakpoint.a(BreakpointLocation.o)
lldb_private::FormatEntity::Format(lldb_private::FormatEntity::Entry const&, lldb_private::Stream&, lldb_private::SymbolContext const*, lldb_private::ExecutionContext const*, lldb_private::Address const*, lldb_private::ValueObject*, bool, bool) in liblldbCore.a(FormatEntity.o)
      lldb_private::ValueObject::Persist() in liblldbCore.a(ValueObject.o)
      lldb_private::ClangExpressionDeclMap::GetStructElement(clang::NamedDecl const*&, llvm::Value*&, unsigned long long&, lldb_private::ConstString&, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangUserExpression::Evaluate(lldb_private::ExecutionContext&, lldb_private::EvaluateExpressionOptions const&, char const*, char const*, lldb_private::SharingPtr<lldb_private::ValueObject>&, lldb_private::Error&) in liblldbExpression.a(ClangUserExpression.o)
      lldb_private::ABI::GetReturnValueObject(lldb_private::Thread&, lldb_private::CompilerType&, bool) const in liblldbTarget.a(ABI.o)
      lldb_private::Target::EvaluateExpression(char const*, lldb_private::StackFrame*, lldb_private::SharingPtr<lldb_private::ValueObject>&, lldb_private::EvaluateExpressionOptions const&) in liblldbTarget.a(Target.o)
      ...
  "lldb_private::ClangExpressionVariable::GetRegisterInfo()", referenced from:
      lldb_private::ClangExpressionDeclMap::AddValueToStruct(clang::NamedDecl const*, lldb_private::ConstString const&, llvm::Value*, unsigned long, unsigned long long) in liblldbExpression.a(ClangExpressionDeclMap.o)
  "lldb_private::ClangExpressionVariable::GetTypeFromUser()", referenced from:
      lldb_private::ClangExpressionDeclMap::AddOneVariable(lldb_private::NameSearchContext&, std::__1::shared_ptr<lldb_private::ClangExpressionVariable>&, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      EntityPersistentVariable::Dematerialize(std::__1::shared_ptr<lldb_private::StackFrame>&, lldb_private::IRMemoryMap&, unsigned long long, unsigned long long, unsigned long long, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
      EntityPersistentVariable::MakeAllocation(lldb_private::IRMemoryMap&, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
  "lldb_private::ClangExpressionVariable::SetCompilerType(lldb_private::CompilerType const&)", referenced from:
      lldb_private::ClangExpressionDeclMap::AddOneFunction(lldb_private::NameSearchContext&, lldb_private::Function*, lldb_private::Symbol*, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionDeclMap::ResolveUnknownTypes() in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(ClangPersistentVariables.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(Materializer.o)
  "lldb_private::ClangExpressionVariable::SetRegisterInfo(lldb_private::RegisterInfo const*)", referenced from:
      lldb_private::ClangExpressionDeclMap::AddOneRegister(lldb_private::NameSearchContext&, lldb_private::RegisterInfo const*, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
  "lldb_private::ClangExpressionVariable::TransferAddress(bool)", referenced from:
      lldb_private::ClangUserExpression::FinalizeJITExecution(lldb_private::Stream&, lldb_private::ExecutionContext&, std::__1::shared_ptr<lldb_private::ClangExpressionVariable>&, unsigned long long, unsigned long long) in liblldbExpression.a(ClangUserExpression.o)
  "lldb_private::ClangExpressionVariable::GetName()", referenced from:
      lldb_private::ClangExpressionDeclMap::AddValueToStruct(clang::NamedDecl const*, lldb_private::ConstString const&, llvm::Value*, unsigned long, unsigned long long) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionDeclMap::GetStructElement(clang::NamedDecl const*&, llvm::Value*&, unsigned long long&, lldb_private::ConstString&, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionDeclMap::AddOneVariable(lldb_private::NameSearchContext&, std::__1::shared_ptr<lldb_private::ClangExpressionVariable>&, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionVariableList::GetVariable(lldb_private::ConstString const&) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangPersistentVariables::RemovePersistentVariable(std::__1::shared_ptr<lldb_private::ClangExpressionVariable>) in liblldbExpression.a(ClangPersistentVariables.o)
      lldb_private::ClangExpressionVariableList::GetVariable(lldb_private::ConstString const&) in liblldbExpression.a(ClangPersistentVariables.o)
      EntityPersistentVariable::Materialize(std::__1::shared_ptr<lldb_private::StackFrame>&, lldb_private::IRMemoryMap&, unsigned long long, lldb_private::Error&) in liblldbExpression.a(Materializer.o)
      ...
  "lldb_private::ClangExpressionVariable::SetName(lldb_private::ConstString const&)", referenced from:
      lldb_private::ClangExpressionDeclMap::AddOneRegister(lldb_private::NameSearchContext&, lldb_private::RegisterInfo const*, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionDeclMap::AddOneFunction(lldb_private::NameSearchContext&, lldb_private::Function*, lldb_private::Symbol*, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(ClangPersistentVariables.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(Materializer.o)
  "lldb_private::ClangExpressionVariable::ClangExpressionVariable(lldb_private::ExecutionContextScope*, lldb::ByteOrder, unsigned int)", referenced from:
      lldb_private::ClangExpressionDeclMap::AddOneRegister(lldb_private::NameSearchContext&, lldb_private::RegisterInfo const*, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionDeclMap::AddOneFunction(lldb_private::NameSearchContext&, lldb_private::Function*, lldb_private::Symbol*, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(ClangPersistentVariables.o)
      lldb_private::ClangExpressionVariableList::CreateVariable(lldb_private::ExecutionContextScope*, lldb_private::ConstString const&, lldb_private::TaggedASTType<1u> const&, lldb::ByteOrder, unsigned int) in liblldbExpression.a(Materializer.o)
  "lldb_private::ClangExpressionVariable::ClangExpressionVariable(lldb_private::ExecutionContextScope*, lldb_private::Value&, lldb_private::ConstString const&, unsigned short)", referenced from:
      lldb_private::ValueObject::Persist() in liblldbCore.a(ValueObject.o)
  "lldb_private::ClangExpressionVariable::ClangExpressionVariable(lldb_private::SharingPtr<lldb_private::ValueObject> const&)", referenced from:
      lldb_private::ClangExpressionDeclMap::AddOneVariable(lldb_private::NameSearchContext&, std::__1::shared_ptr<lldb_private::Variable>, lldb_private::SharingPtr<lldb_private::ValueObject>, unsigned int) in liblldbExpression.a(ClangExpressionDeclMap.o)
      lldb_private::ClangPersistentVariables::CreatePersistentVariable(lldb_private::SharingPtr<lldb_private::ValueObject> const&) in liblldbExpression.a(ClangPersistentVariables.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [usr/lib/libcxxffi.dylib] Error 1
========================================================[ ERROR: Cxx ]=========================================================

LoadError: failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/Users/ranjan/julia-4/usr/bin`, ProcessExited(2)) [2]
while loading /Users/ranjan/.julia/v0.4/Cxx/deps/build.jl, in expression starting on line 16

===============================================================================================================================

=======================================================[ BUILD ERRORS ]========================================================

WARNING: Cxx had build errors.

 - packages with build errors remain installed in /Users/ranjan/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

===============================================================================================================================

```

**Comment by Keno** [comment] 2015-09-03 19:15
I suspect this is caused by LLDB reorganizing some libraries, creating new ones which are not currently being linked in. This should be quite simple to fix, so why don't you or @nkottary try to have a go at it.

**Comment by Keno** [comment] 2015-09-20 04:11
Fixed now.

**Closed by Keno** 2015-09-20 04:11 UTC
