### ISSUE TITLE
LLVM Build failure in OSX

### ISSUE THREAD

**Issue by sbromberger** [Keno/Cxx.jl#182] opened 2015-10-24 03:02 UTC
```
llvm[6]: Compiling CGCXX.cpp for Release+Asserts build
/Users/seth/dev/julia/julia/deps/llvm-svn/tools/clang/lib/CodeGen/CGCXX.cpp:193:7: error: no matching function for call to 'create'
      llvm::GlobalAlias::create(AliasType, Linkage, "", Aliasee, &getModule());
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/seth/dev/julia/julia/deps/llvm-svn/include/llvm/IR/GlobalAlias.h:51:23: note: candidate function not viable: no known
      conversion from 'const char [1]' to 'llvm::GlobalValue::LinkageTypes' for 3rd argument
  static GlobalAlias *create(Type *Ty, unsigned AddressSpace,
                      ^
/Users/seth/dev/julia/julia/deps/llvm-svn/include/llvm/IR/GlobalAlias.h:56:23: note: candidate function not viable: no known
      conversion from 'const char [1]' to 'llvm::GlobalValue::LinkageTypes' for 3rd argument
  static GlobalAlias *create(Type *Ty, unsigned AddressSpace,
                      ^
/Users/seth/dev/julia/julia/deps/llvm-svn/include/llvm/IR/GlobalAlias.h:46:23: note: candidate function not viable: requires 6
      arguments, but 5 were provided
  static GlobalAlias *create(Type *Ty, unsigned AddressSpace,
                      ^
/Users/seth/dev/julia/julia/deps/llvm-svn/include/llvm/IR/GlobalAlias.h:61:23: note: candidate function not viable: requires 3
      arguments, but 5 were provided
  static GlobalAlias *create(LinkageTypes Linkage, const Twine &Name,
                      ^
/Users/seth/dev/julia/julia/deps/llvm-svn/include/llvm/IR/GlobalAlias.h:65:23: note: candidate function not viable: requires 2
      arguments, but 5 were provided
  static GlobalAlias *create(const Twine &Name, GlobalValue *Aliasee);
                      ^
1 error generated.
make[6]: *** [/Users/seth/dev/julia/julia/deps/llvm-svn/build_Release+Asserts/tools/clang/lib/CodeGen/Release+Asserts/CGCXX.o] Error 1
```

This is on release-0.4 with the Make.user overrides.

**Comment by sbromberger** [comment] 2015-10-24 03:16
(sorry for the raw dump of the error; I don't know where to begin to troubleshoot. Google doesn't show anything for this specific issue.)

**Comment by Keno** [comment] 2015-10-24 07:25
I know what the issue is. I'm in the process of balloting a few fixes to 0.4

**Comment by malmaud** [comment] 2015-10-25 17:38
Thanks Keno. I wonder if in the meantime, there's some combination of settings to Make.user and a commit of Julia that will work.

**Comment by Keno** [comment] 2015-10-25 17:40
You can manually check out deps/srccache/llvm-svn/tools/clang to kf/gallium. You will probably also have to revert Jeff's change to enable the new SROA pass

**Comment by Keno** [comment] 2015-10-26 07:13
Should be fixed by my latest commit to llvm master and the pending backport to release-0.4, you'll have to delete `deps/(srccache/)llvm-svn`.

**Closed** 2015-10-26 07:35 UTC

**Comment by malmaud** [comment] 2015-10-30 00:18
It looks like your pending-backport branch was deleted. Which Julia commit should we be using now to go along with the current suggested Make.user?

**Comment by malmaud** [comment] 2015-10-30 00:54
NM, I see it's been merged into release-0.4

**Comment by sbromberger** [comment] 2015-10-30 01:25
Getting

```
Branch kf/gallium set up to track remote branch kf/gallium from origin.
Switched to a new branch 'kf/gallium'
Cloning into 'llvm-svn/tools/lldb'...
remote: Counting objects: 141811, done.
remote: Total 141811 (delta 0), reused 0 (delta 0), pack-reused 141811
Receiving objects: 100% (141811/141811), 72.73 MiB | 11.09 MiB/s, done.
Resolving deltas: 100% (106792/106792), done.
Checking connectivity... done.
/bin/sh: line 0: cd: svn/tools/lldb: No such file or directory
make[1]: *** [llvm-svn/configure] Error 1
make: *** [julia-deps] Error 2
```
now (on a fresh `release-0.4` pull).

**Comment by malmaud** [comment] 2015-10-30 14:24
Ya, I'm not sure how to get any combination of Cxx.jl, Make.user settings, and a Julia commit working now.

**Comment by Keno** [comment] 2015-11-01 00:50
Both 0.4 and master should work now, though I can't guarantee the latter will keep working.

**Comment by malmaud** [comment] 2015-11-01 01:44
release-0.4 and the Gallium LLVM branch, or upstream LLVM master?

**Comment by Keno** [comment] 2015-11-01 01:55
Julia release-0.4/Julia master both with Gallium LLVM branch.

**Comment by malmaud** [comment] 2015-11-01 01:56
Great, thanks.

**Comment by sbromberger** [comment] 2015-11-01 04:46
Now getting

```
llvm[6]: Compiling macosx/Host.mm for Release+Asserts build
In file included from /Users/seth/dev/julia/julia/deps/llvm-svn/tools/lldb/source/Host/macosx/Host.mm:75:
In file included from /Users/seth/dev/julia/julia/deps/llvm-svn/tools/lldb/source/Host/macosx/cfcpp/CFCBundle.h:13:
/Users/seth/dev/julia/julia/deps/llvm-svn/tools/lldb/source/Host/macosx/cfcpp/CFCReleaser.h:13:10: fatal error:
      'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^
1 error generated.
rm: /Users/seth/dev/julia/julia/deps/llvm-svn/build_Release+Asserts/tools/lldb/source/Host/Release+Asserts/macosx/Host.d.tmp: No such file or directory
make[6]: *** [/Users/seth/dev/julia/julia/deps/llvm-svn/build_Release+Asserts/tools/lldb/source/Host/Release+Asserts/macosx/Host.o] Error 1
```

**Comment by Keno** [comment] 2015-11-01 04:47
Is XCode installed and up to date? Also, if you just want Cxx.jl, you can disable the BUILD_LLDB part of Make.user

**Comment by sbromberger** [comment] 2015-11-01 04:48
XCode is installed: Version 7.0.1 (7A1001)

I'd like to try Gallium as well, but Cxx.jl is my main focus now.

**Comment by Keno** [comment] 2015-11-01 04:51
Try running `xcode-select --install` just to make sure the command line tools agree with the xcode version.

**Comment by sbromberger** [comment] 2015-11-01 04:52
weird. That seemed to fix it. At least the build has resumed. Thanks!

**Comment by sbromberger** [comment] 2015-11-01 18:50
It built, though with a strange warning:

```
/Users/seth/dev/julia/julia/base/precompile.jl
    LINK usr/lib/julia/sys.dylib
ld: warning: object file (/Users/seth/dev/julia/julia/usr/lib/julia/sys.o) was built for newer OSX version (15.0) than being linked (10.7)
    CC usr/lib/libccalltest.dylib
```
